### ISSUE TITLE
Deprecate this tap

### ISSUE THREAD

**Issue by jonasmalacofilho** [jonasmalacofilho/homebrew-liquidctl#2]
@CaseySJ 

I'm thinking about deprecating this tap.  Many of the reasons for keeping it are gone now, and it's always breaking (usually in Linuxbrew).

First, we now have official liquidctl formulas on both homebrew-core and linuxbrew-core.  Sure, the Linuxbrew formula is almost certainly broken due to a hardcoded path in cython-hidapi, but it's more productive to fix that there.

And while the tap also enabled us to push release candidates to our users, I've since stopped doing RCs: they never got enough testing (particularly on the platforms more likely to break), so it's just simpler to assume that a few patch releases will be necessary.

What do you think?

---

Practically we can't just drop it, because there might be users relying on it.  In the mean time, and besides removing any mentions to it, we could also try to make the formula emit a warning message during installation.

Something like "The jonasmalacofilho/liquidctl tap has been deprecated; to switch to the official liquidctl formula in homebrew-core, do [...]".

**Comment by CaseySJ** [comment]
I agree -- we should emit a warning for users to switch to homebrew-core and then discontinue the tap after perhaps one more update...

**Comment by jonasmalacofilho** [comment]
I propose we keep updating this only for eventual (new) 1.3.x patch releases.
